// import "bootstrap/dist/js/bootstrap.bundle.min.js" Error occurred
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.scss'
import "./globalStyles.scss"

import type { Metadata } from 'next'
import InitializedUserContextProvider from './context';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <InitializedUserContextProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </InitializedUserContextProvider>
  )
}
